# POST

POST http://localhost:3333/transaction
Content-Type: application/json

{
  "value": 2443.45,
  "dateTime": "2025-06-11T21:20"
}

###

# GET
GET http://localhost:3333/transaction


###

# DELETE
DELETE http://localhost:3333/transaction