# POST TRANSACTIONS
POST http://localhost:3333/transaction
Content-Type: application/json

{
  "value": 20.0,
  "dateTime": "2025-06-13T01:13:20"
}

###
# GET TRANSACTIONS
GET http://localhost:3333/transaction


###
# DELETE TRANSACTIONS
DELETE http://localhost:3333/transaction

###

# GET STATISTICS
GET http://localhost:3333/statistics